spring:
  application:
    name: CLIENT-SERVICES
server:
  port: 9191
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: INFO
  pattern:
  #    file: [ %d{yyyy-MM-dd HH:mm:ss} ][ %level ][ %thread ] --- [ %logger{36} ][ %logger{1.} ] :=> %msg%n
  #    console: [ %d{yyyy-MM-dd HH:mm:ss} ][ %level ][ %thread ] --- [ %logger{36} ][ %logger{1.} ] :=> %msg%n
  file:
    name: D:\aSpringBoot\ProjectPractice\AppLogs\CLIENT_SERVICES.log